### ISSUE TITLE
第二章react-node,执行npm start 的时候出现这个报错

### ISSUE THREAD

**Issue by ghost** [lewis617/react-redux-book#10]
$ npm start

> react-node@1.0.0 start D:\reactjs\React与Redux开发实例\recat-node
> node index

D:\reactjs\React与Redux开发实例\recat-node\node_modules\babel-core\lib\transformation\file\index.js:590
      throw err;
      ^

SyntaxError: D:\reactjs\React与Redux开发实例\recat-node\src\server.js: Unexpected token (12:31)
  10 | import App from './App';
  11 |
> 12 | const appHTML = renderToString(<App />);
     |                                ^
  13 |
  14 | console.log(appHTML);
    at Parser.pp$5.raise (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:4373:13)
    at Parser.pp.unexpected (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:1716:8)
    at Parser.pp$3.parseExprAtom (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:3683:12)
    at Parser.pp$3.parseExprSubscripts (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:3427:19)
    at Parser.pp$3.parseMaybeUnary (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:3407:19)
    at Parser.pp$3.parseExprOps (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:3337:19)
    at Parser.pp$3.parseMaybeConditional (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:3314:19)
    at Parser.pp$3.parseMaybeAssign (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:3277:19)
    at Parser.pp$3.parseExprListItem (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:4231:16)
    at Parser.pp$3.parseCallExpressionArguments (D:\reactjs\React与Redux开发实例\recat-node\node_modules\babylon\lib\index.js:3506:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-node@1.0.0 start: `node index`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-node@1.0.0 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-node
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     F:\nodejs\node_cache\_logs\2017-03-17T13_34_14_347Z-debug.log

**Comment by lewis617** [comment]
刚刚测试了一下，没问题。再给点别的信息？

**Comment by ghost** [comment]
@lewis617 我windows系统下node版本是v6.10.0  npm版本是v4.1.1   目录结构除了执行npm init 那个node_modules文件夹和package.json文件之外其他的跟你的一致
package.json内容是：
{
  "name": "react-node",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node index"
  },
  "author": "FECat",
  "license": "MIT",
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "babel-register": "^6.24.0"
  }
}

**Comment by lewis617** [comment]
我看了下，可能是babel升级导致的：

你的版本：
```json
"devDependencies": {
    "babel-core": "^6.24.0",
    "babel-preset-es2015": "^6.24.0",
    "babel-preset-react": "^6.23.0",
    "babel-register": "^6.24.0"
  }
```
书中版本：

```json
"devDependencies": {
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-register": "^6.8.0"
  },
```

建议复制粘贴书中的版本，先让程序运行起来，然后自行查找升级方案，逐步进行升级。

如何安装指定版本：

```sh
npm install babel-preset-es2015@^6.6.0
```

为何不更新书中版本？因为示例代码和纸质书是配套的，所以无法及时更新版本。但日后会考虑新开一个latest分支，盛放最新版本的示例代码。
