### ISSUE TITLE
19-3-isomophic-counter 这一章节的时候报错

### ISSUE THREAD

**Issue by aikeProject** [lewis617/react-redux-book#13]
> 19-3-isomophic-counter@0.0.0 start F:\myStudy\react-rudux-book-study\19-3-isomophic-counter
> concurrently -k "node server/dev-server.js" "node server/index.js"

[0] ==> 🚧  Webpack development server listening on port 3001.
[1] ==> 🌎  Listening on port 3000. Open up http://localhost:3000/ in your browser.
[0] Hash: d213f427a99e368beccd
[0] Version: webpack 1.15.0
[0] Time: 3693ms
[0]     Asset    Size  Chunks             Chunk Names
[0] bundle.js  3.2 MB       0  [emitted]  main
[0] webpack built d213f427a99e368beccd in 3693ms
[1] [webpack-isomorphic-tools] [error] asset not found: ./common/components/Counter.css
[1] F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\common\components\Counter.js:30
[1]       className: require('./Counter.css').counter
[1]                                          ^
[1]
[1] TypeError: Cannot read property 'counter' of undefined
[1]     at Counter (F:/myStudy/react-rudux-book-study/19-3-isomophic-counter/common/components/Counter.js:10:20)
[1]     at F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:303:16
[1]     at measureLifeCyclePerf (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:73:12)
[1]     at ReactCompositeComponentWrapper._constructComponentWithoutOwner (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:302:14)
[1]     at ReactCompositeComponentWrapper._constructComponent (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:277:21)
[1]     at ReactCompositeComponentWrapper.mountComponent (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:185:21)
[1]     at Object.mountComponent (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactReconciler.js:43:35)
[1]     at ReactCompositeComponentWrapper.performInitialMount (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:368:34)
[1]     at ReactCompositeComponentWrapper.mountComponent (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactCompositeComponent.js:255:21)
[1]     at Object.mountComponent (F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\node_modules\_react-dom@15.6.2@react-dom\lib\ReactReconciler.js:43:35)
[1] node server/index.js exited with code 1
--> Sending SIGTERM to other processes..
[0] node server/dev-server.js exited with code 1

npm ERR! Windows_NT 10.0.16299
npm ERR! argv "E:\\Program Files\\nodejs\\node.exe" "E:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! 19-3-isomophic-counter@0.0.0 start: `concurrently -k "node server/dev-server.js" "node server/index.js"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 19-3-isomophic-counter@0.0.0 start script 'concurrently -k "node server/dev-server.js" "node server/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the 19-3-isomophic-counter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently -k "node server/dev-server.js" "node server/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 19-3-isomophic-counter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 19-3-isomophic-counter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\myStudy\react-rudux-book-study\19-3-isomophic-counter\npm-debug.log

我将报错那行先去除，能跑起来，但是把去掉的加上之后运行，控制台报错如下：

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) ElFTkSuQmCC" class="_3zfCozKjFrABEgorq3y
 (server) ElFTkSuQmCC" class="require('./Counter.c

**Comment by lewis617** [comment]
刚才测试了一下，无法复现你描述的问题，或许你可以尝试用 Yarn 代替 npm，npm太慢了，也不要用 tnpm，因为有些国外的小轮子造的不规范，和tnpm 不兼容。

你进入这个章节目录下，执行：

```sh
yarn
```
等待安装完成后，执行：

```sh
npm start
```

**Comment by aikeProject** [comment]
我之前是通过cnpm安装的依赖，很可能是依赖版本的问题
通过yarn安装依赖再运行，没有报错了

**Comment by aikeProject** [comment]
正在看你的书，^~^

**Comment by lewis617** [comment]
好的，解决问题就好～

**Comment by trust2065** [comment]
直接複製repo後使用yarn安裝執行, 
會得到`[1] [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)     `的infinite loop

```
C:\...  (19-3-isomophic-counter@0.0.0)                                                      
λ yarn                                                                                                                                            
yarn install v1.12.3                                                                                                                              
info No lockfile found.                                                                                                                           
[1/4] Resolving packages...                                                                                                                       
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!    
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tool
s.                                                                                                                                                
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in oth
er tools.                                                                                                                                         
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 conf
ig used in other tools.                                                                                                                           
[2/4] Fetching packages...                                                                                                                        
info fsevents@1.2.4: The platform "win32" is incompatible with this module.                                                                       
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.                                   
[3/4] Linking dependencies...                                                                                                                     
[4/4] Building fresh packages...                                                                                                                  
success Saved lockfile.                                                                                                                           
Done in 66.23s.                                                                                                                                   
                                                                                                                                                  
C:\...  (19-3-isomophic-counter@0.0.0)                                                           
λ yarn start                                                                                                                                      
yarn run v1.12.3                                                                                                                                  
$ concurrently -k "node server/dev-server.js" "node server/index.js"                                                                              
[0] ==> 🚧  Webpack development server listening on port 3001.                                                                                    
[1] [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)                                                                    
[1] [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)                                                                    
[1] [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)                                                                    
[1] [webpack-isomorphic-tools] (waiting for the first Webpack build to finish)                                                                    
Terminate batch job (Y/N)? y                                                                                                                      `
