### ISSUE TITLE
ERROR in ./~/bootstrap-loader/lib/bootstrap.loader.js!./~/bootstrap-loader/no-op.js

### ISSUE THREAD

**Issue by dean20160218** [lewis617/react-redux-book#15]
Module build failed: Error: Cannot find module '/Users/dinghao/Documents/react-redux-book/22-bootstrap/node_modules/bootstrap-sass/package.json/package.json'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at exports.default (/Users/test/Documents/react-redux-book/22-bootstrap/node_modules/bootstrap-loader/lib/utils/checkBootstrapVersion.js:8:20)
    at Object.module.exports.pitch (/Users/dinghao/Documents/react-redux-book/22-bootstrap/node_modules/bootstrap-loader/lib/bootstrap.loader.js:155:65)
 @ ./~/bootstrap-loader/loader.js 1:17-61

有人知道这个问题如何解决吗？谢谢！

**Comment by lewis617** [comment]
请使用配置了 淘宝源 yarn 来安装依赖。具体方法：
（逐条执行）
```
npm i yarn -g
npm i yrm -g
yrm use taobao
yarn
```

**Comment by dean20160218** [comment]
https://github.com/shakacode/bootstrap-loader/issues/341 
问题得到解决。Resolve@1.7.0

**Comment by lewis617** [comment]
@dean20160218 好的，问题解决就好
