### ISSUE TITLE
19-3-isomophic-counter的例子跑不了

### ISSUE THREAD

**Issue by aosp-11-lubancat** [lewis617/react-redux-book#4]
```
concurrently -k "node server/dev-server.js" "node server/index.js"

[0] ==> 🚧  Webpack development server listening on port 3001.
[1] ==> 🌎  Listening on port 3000. Open up http://localhost:3000/ in your browser.
[0] Hash: 358684a66363b78eccf7
[0] Version: webpack 1.14.0
[0] Time: 4540ms
[0]     Asset    Size  Chunks             Chunk Names
[0] bundle.js  3.1 MB       0  [emitted]  main
[0] webpack built 358684a66363b78eccf7 in 4540ms
[1] [webpack-isomorphic-tools] [error] asset not found: ./common/components/Counter.css
[1] /Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/common/components/Counter.js:26
[1]       className: require('./Counter.css').counter
[1]                                          ^
[1] 
[1] TypeError: Cannot read property 'counter' of undefined
[1]     at Counter (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/common/components/Counter.js:9:20)
[1]     at /Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactCompositeComponent.js:306:16
[1]     at measureLifeCyclePerf (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactCompositeComponent.js:75:12)
[1]     at ReactCompositeComponentWrapper._constructComponentWithoutOwner (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactCompositeComponent.js:305:14)
[1]     at ReactCompositeComponentWrapper._constructComponent (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactCompositeComponent.js:280:21)
[1]     at ReactCompositeComponentWrapper.mountComponent (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactCompositeComponent.js:188:21)
[1]     at Object.mountComponent (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactReconciler.js:46:35)
[1]     at ReactCompositeComponentWrapper.performInitialMount (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactCompositeComponent.js:371:34)
[1]     at ReactCompositeComponentWrapper.mountComponent (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactCompositeComponent.js:258:21)
[1]     at Object.mountComponent (/Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/node_modules/.15.4.1@react-dom/lib/ReactReconciler.js:46:35)
[1] node server/index.js exited with code 1
--> Sending SIGTERM to other processes..
[0] node server/dev-server.js exited with code null

npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/shiki/.nvm/versions/node/v7.1.0/bin/node" "/Users/shiki/.nvm/versions/node/v7.1.0/lib/node_modules/npm/bin/npm-cli.js" "run" "start"
npm ERR! node v7.1.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! 19-3-isomophic-counter@0.0.0 start: concurrently -k "node server/dev-server.js" "node server/index.js"
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the 19-3-isomophic-counter@0.0.0 start script 'concurrently -k "node server/dev-server.js" "node server/index.js"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the 19-3-isomophic-counter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     concurrently -k "node server/dev-server.js" "node server/index.js"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 19-3-isomophic-counter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 19-3-isomophic-counter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/shiki/workspace_node_servcie/react-redux-book/19-3-isomophic-counter/npm-debug.log

Process finished with exit code 1
```

打开游览器访问 http://localhost:3000 /整个服务就抛异常 说找不到./common/components/Counter.css 不知道是不是例子配置出错 还是我少打命令  因为已经用 cnpm i 然后在运行
package.json的start命令 前面章节的例子我没跑 我只跑这个例子

**Comment by lewis617** [comment]
刚才在win、mac、linux测试了一遍没有问题。

或许你可以这么做：

别用cnpm，国外有些开发者的轮子写得不规范，跟cnpm不兼容（当然，我也用cnpm测试了，没问题，cnpm是跟bootstrap-loader那个库不兼容）。使用配置了淘宝源的yarn或npm。

**Comment by aosp-11-lubancat** [comment]
@lewis617 解决了 就是因为cnpm的原因....用npm就没问题
