### ISSUE TITLE
使用webpack2.x 跑 watch-client 那个任务报错

### ISSUE THREAD

**Issue by Jafeney** [lewis617/react-redux-book#9]
使用webpack2.x 跑 watch-client 那个任务报错：

```
/Users/jafeney/Desktop/framework/node_modules/webpack/lib/webpack.js:19
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'progress'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           progress: ...
         }
       })
     ]
    at webpack (/Users/jafeney/Desktop/framework/node_modules/webpack/lib/webpack.js:19:9)
    at Object.<anonymous> (/Users/jafeney/Desktop/framework/webpack/webpack-dev-server.js:14:16)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
```

问题应该是出在 `./webpack/dev.config.js` 对 `postcss`定义 在webpack2.x里不适用  

```
...

postcss: [autoprefixer({ browsers: ['last 2 versions'] })]

...

```

虽然webpack降低版本到1.x 就OK了，但还是希望能与时俱进，还请大伙支招 (^^)

**Comment by lewis617** [comment]
由于纸质书无法及时更新，所以目前为止，示例代码依旧打算使用与书中对应的webpack 1.x版本。如在实际生产中需要使用webpack2.x，可以自行按照官方升级指南进行升级。
